# Generated by Django 5.1.4 on 2025-01-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name", max_length=100, null=True)),
                ('last_name', models.CharField(help_text="User's last name", max_length=100, null=True)),
                ('email_id', models.EmailField(blank=True, help_text="User's email address", max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, help_text="User's password", max_length=100, null=True)),
                ('confirm_password', models.CharField(blank=True, help_text="Confirm user's password", max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Profile picture of the user', null=True, upload_to='media')),
                ('department', models.CharField(blank=True, help_text='Department of the user (e.g., IT, HR, etc.)', max_length=100, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience in the work role', null=True)),
                ('work_role', models.CharField(blank=True, help_text='Work role or job title (e.g., Software Engineer, Manager)', max_length=100, null=True)),
            ],
        ),
    ]
