# Generated by Django 5.1.4 on 2025-01-29 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('responses', models.JSONField()),
                ('stress_score', models.IntegerField()),
                ('recommendations', models.TextField()),
            ],
        ),
    ]
