# Generated by Django 5.1.4 on 2025-02-22 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stressassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressassessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usersregister'),
        ),
    ]
