# Generated by Django 5.1.6 on 2025-02-28 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_name', models.CharField(help_text='Name of the application', max_length=100)),
                ('usage_duration', models.DurationField(help_text='Duration of app usage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('keystrokes_per_minute', models.IntegerField(help_text='Number of keystrokes per minute')),
                ('typing_duration', models.DurationField(help_text='Duration of typing activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(help_text='Total screen time duration')),
                ('application', models.CharField(blank=True, help_text='Application in focus', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='VoicePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio_file', models.FileField(blank=True, help_text='Recorded voice sample', null=True, upload_to='voice_patterns/')),
                ('stress_level', models.FloatField(blank=True, help_text='Estimated stress level from voice analysis', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('FITBIT', 'Fitbit'), ('APPLE_WATCH', 'Apple Watch'), ('OTHER', 'Other')], help_text='Type of wearable device', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in beats per minute', null=True)),
                ('steps', models.IntegerField(blank=True, help_text='Number of steps taken', null=True)),
                ('sleep_duration', models.DurationField(blank=True, help_text='Sleep duration', null=True)),
                ('stress_indicator', models.FloatField(blank=True, help_text='Stress indicator from wearable data', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
    ]
