# Generated by Django 4.2.20 on 2025-03-21 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('VIDEO', 'Video'), ('ARTICLE', 'Article'), ('AUDIO', 'Audio'), ('EXERCISE', 'Exercise')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
            ],
        ),
        migrations.CreateModel(
            name='UsersRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name", max_length=100, null=True)),
                ('last_name', models.CharField(help_text="User's last name", max_length=100, null=True)),
                ('email_id', models.EmailField(blank=True, help_text="User's email address", max_length=254, null=True, unique=True)),
                ('password', models.CharField(blank=True, help_text="User's password", max_length=100, null=True)),
                ('confirm_password', models.CharField(blank=True, help_text="Confirm user's password", max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Profile picture of the user', null=True, upload_to='media')),
                ('department', models.CharField(blank=True, help_text='Department of the user (e.g., IT, HR, etc.)', max_length=100, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience in the work role', null=True)),
                ('work_role', models.CharField(blank=True, help_text='Work role or job title (e.g., Software Engineer, Manager)', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('FITBIT', 'Fitbit'), ('APPLE_WATCH', 'Apple Watch'), ('OTHER', 'Other')], help_text='Type of wearable device', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in beats per minute', null=True)),
                ('steps', models.IntegerField(blank=True, help_text='Number of steps taken', null=True)),
                ('sleep_duration', models.DurationField(blank=True, help_text='Sleep duration', null=True)),
                ('stress_indicator', models.FloatField(blank=True, help_text='Stress indicator from wearable data', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='VoicePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio_file', models.FileField(blank=True, help_text='Recorded voice sample', null=True, upload_to='voice_patterns/')),
                ('stress_level', models.FloatField(blank=True, help_text='Estimated stress level from voice analysis', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='StressAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('responses', models.TextField()),
                ('stress_score', models.IntegerField()),
                ('recommendations', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(help_text='Total screen time duration')),
                ('application', models.CharField(blank=True, help_text='Application in focus', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(help_text='Personalized recommendation content')),
                ('category', models.CharField(choices=[('BREAK', 'Take a Break'), ('EXERCISE', 'Exercise'), ('MINDFULNESS', 'Mindfulness'), ('SCHEDULE', 'Schedule Adjustment'), ('RESOURCE', 'Resource')], max_length=50)),
                ('priority', models.IntegerField(default=1, help_text='Priority level (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('stress_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stressassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('keystrokes_per_minute', models.IntegerField(help_text='Number of keystrokes per minute')),
                ('typing_duration', models.DurationField(help_text='Duration of typing activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stressassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_name', models.CharField(help_text='Name of the application', max_length=100)),
                ('usage_duration', models.DurationField(help_text='Duration of app usage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Alert message for high stress')),
                ('threshold', models.IntegerField(help_text='Stress score threshold that triggered this alert')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersregister')),
            ],
        ),
    ]
