# Generated by Django 4.2.20 on 2025-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersregister',
            name='confirm_password_token',
            field=models.CharField(blank=True, help_text='Token for password reset', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='usersregister',
            name='confirm_password',
            field=models.CharField(blank=True, help_text="Confirm user's password", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersregister',
            name='password',
            field=models.CharField(blank=True, help_text="User's password", max_length=255, null=True),
        ),
    ]
