# Generated by Django 4.2.20 on 2025-03-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usersregister_confirm_password_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersregister',
            name='confirm_password_token',
        ),
    ]
