# Generated by Django 4.2.20 on 2025-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usersregister_confirm_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersregister',
            name='confirm_password_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
